# Generated by Django 3.2.9 on 2022-02-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='region',
            field=models.CharField(default='LAN', max_length=5),
            preserve_default=False,
        ),
    ]
