# Generated by Django 3.2.9 on 2022-06-24 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0002_summoner_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summoner',
            name='level',
        ),
        migrations.AddField(
            model_name='game',
            name='gamedate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SummonerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winrate', models.FloatField()),
                ('winstreak', models.IntegerField()),
                ('meankda', models.FloatField()),
                ('tier', models.IntegerField()),
                ('division', models.IntegerField()),
                ('level', models.IntegerField()),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summoners.summoner')),
            ],
        ),
    ]
