# Generated by Django 3.2.9 on 2022-06-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0003_auto_20220624_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gamedate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
