# Generated by Django 3.2.9 on 2022-06-25 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0001_initial'),
        ('summoners', '0004_alter_game_gamedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerecord',
            name='champion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='champions.champion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='win',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
