# Generated by Django 3.2.9 on 2022-06-28 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0001_initial'),
        ('summoners', '0005_auto_20220624_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummonerChampionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championpoints', models.IntegerField()),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='champions.champion')),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summoners.summoner')),
            ],
        ),
    ]
