# Generated by Django 3.2.9 on 2022-06-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0006_summonerchampionstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerecord',
            name='kda',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
