# Generated by Django 3.2.9 on 2021-12-08 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
