# Generated by Django 3.2.9 on 2022-06-28 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='key',
        ),
        migrations.AddField(
            model_name='champion',
            name='championid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
